// src/components/vue/PdfEditor.vue
<template>
  <div class="pdf-editor-wrapper">
    <div class="editor-header">
      <h3 class="editor-title">文档编辑</h3>
      <div class="header-actions">
        <button 
          v-if="hasPDF" 
          @click="removeWatermark" 
          class="action-btn watermark-btn"
          :disabled="isProcessing"
        >
          {{ isProcessing ? '处理中...' : '去除水印' }}
        </button>
        <button 
          @click="exportPDF" 
          class="action-btn export-btn"
          :disabled="!hasContent"
        >
          导出PDF
        </button>
      </div>
    </div>

    <div class="toolbar-section">
      <input
        type="file"
        ref="fileInput"
        accept=".pdf"
        @change="handleFileUpload"
        style="display: none"
      />
      <button @click="triggerFileInput" class="upload-btn">
        <span class="icon">📄</span>
        上传PDF文件
      </button>
      
      <div v-if="fileName" class="file-info">
        <span class="file-name">{{ fileName }}</span>
        <button @click="clearFile" class="clear-btn">×</button>
      </div>
    </div>

    <div class="editor-container">
      <div ref="editorRef" class="rich-text-editor"></div>
    </div>

    <div v-if="watermarks.length > 0" class="watermark-panel">
      <h4>检测到的水印：</h4>
      <ul>
        <li v-for="(wm, index) in watermarks" :key="index">
          {{ wm.content }}
          <button @click="removeSpecificWatermark(index)" class="remove-wm-btn">移除</button>
        </li>
      </ul>
    </div>

    <div class="image-replace-section" v-if="hasPDF">
      <h4>图片替换</h4>
      <input
        type="file"
        ref="imageInput"
        accept="image/*"
        @change="handleImageReplace"
        style="display: none"
      />
      <button @click="triggerImageInput" class="replace-image-btn">
        选择新图片替换
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, nextTick } from 'vue'
import { PDFParser, PDFModifier, WatermarkInfo } from '../../core/pdf-parser'
import { RichTextEditor, EditorConfig } from '../../core/rich-text-editor'

interface Props {
  placeholder?: string
  readOnly?: boolean
  initialContent?: string
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: '请输入或粘贴PDF内容...',
  readOnly: false,
  initialContent: ''
})

const emit = defineEmits<{
  'content-change': [data: { html: string; delta: any }]
  'pdf-loaded': [data: { pages: any[]; watermarks: WatermarkInfo[] }]
  'pdf-exported': [pdfBytes: Uint8Array]
  'error': [error: any]
}>()

const editorRef = ref<HTMLElement | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)
const imageInput = ref<HTMLInputElement | null>(null)
const fileName = ref<string>('')
const hasPDF = ref<boolean>(false)
const hasContent = ref<boolean>(false)
const isProcessing = ref<boolean>(false)
const watermarks = ref<WatermarkInfo[]>([])

let editor: RichTextEditor | null = null
let pdfParser: PDFParser | null = null
let pdfModifier: PDFModifier | null = null

const triggerFileInput = () => {
  fileInput.value?.click()
}

const triggerImageInput = () => {
  imageInput.value?.click()
}

onMounted(() => {
  if (editorRef.value) {
    const config: EditorConfig = {
      placeholder: props.placeholder,
      readOnly: props.readOnly,
      onContentChange: (html: string, delta: any) => {
        hasContent.value = !!html && html !== '<p><br></p>'
        emit('content-change', { html, delta })
      },
      onImageUpload: async (file: File): Promise<string> => {
        return new Promise((resolve) => {
          const reader = new FileReader()
          reader.onload = (e) => resolve(e.target?.result as string)
          reader.readAsDataURL(file)
        })
      }
    }

    editor = new RichTextEditor(editorRef.value, config)

    if (props.initialContent) {
      editor.setContent(props.initialContent)
      hasContent.value = true
    }
  }

  pdfParser = new PDFParser()
  pdfModifier = new PDFModifier()
})

onBeforeUnmount(() => {
  if (editor) {
    editor.destroy()
  }
})

const handleFileUpload = async (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  
  if (file && file.type === 'application/pdf') {
    try {
      fileName.value = file.name
      isProcessing.value = true
      
      const pages = await pdfParser!.loadPDF(file)
      hasPDF.value = true
      
      let fullContent = ''
      pages.forEach((page, index) => {
        if (index > 0) fullContent += '<br/><br/>'
        fullContent += `<h2>第 ${page.pageNumber} 页</h2>`
        fullContent += `<p>${page.textContent}</p>`
      })
      
      await nextTick()
      editor?.setContent(fullContent)
      hasContent.value = true
      
      const detectedWatermarks = await pdfParser!.detectWatermarks()
      watermarks.value = detectedWatermarks
      
      emit('pdf-loaded', { pages, watermarks: detectedWatermarks })
    } catch (error) {
      console.error('PDF loading error:', error)
      emit('error', error)
    } finally {
      isProcessing.value = false
    }
  }
}

const handleImageReplace = async (event: Event) => {
  const target = event.target as HTMLInputElement
  const file = target.files?.[0]
  
  if (file && pdfParser?.getPDFBytes()) {
    try {
      isProcessing.value = true
      await pdfModifier!.replaceImage(
        pdfParser.getPDFBytes()!,
        0,
        file
      )
      alert('图片已准备替换，导出时将生效')
    } catch (error) {
      console.error('Image replacement error:', error)
      emit('error', error)
    } finally {
      isProcessing.value = false
    }
  }
}

const removeWatermark = async () => {
  if (!pdfParser?.getPDFBytes() || !watermarks.value.length) return
  
  try {
    isProcessing.value = true
    const watermarkTexts = watermarks.value.map(wm => wm.content)
    await pdfModifier!.removeWatermark(pdfParser.getPDFBytes()!, watermarkTexts)
    watermarks.value = []
    alert('水印已移除，将在导出时生效')
  } catch (error) {
    console.error('Watermark removal error:', error)
    emit('error', error)
  } finally {
    isProcessing.value = false
  }
}

const removeSpecificWatermark = async (index: number) => {
  const wm = watermarks.value[index]
  if (!pdfParser?.getPDFBytes()) return
  
  try {
    isProcessing.value = true
    await pdfModifier!.removeWatermark(pdfParser.getPDFBytes()!, [wm.content])
    watermarks.value.splice(index, 1)
  } catch (error) {
    console.error('Error removing watermark:', error)
    emit('error', error)
  } finally {
    isProcessing.value = false
  }
}

const exportPDF = async () => {
  if (!editor || !hasContent.value) return
  
  try {
    isProcessing.value = true
    const content = editor.getContent()
    const pdfBytes = await pdfModifier!.exportToPDF(content)
    
    const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `edited-document-${Date.now()}.pdf`
    a.click()
    URL.revokeObjectURL(url)
    
    emit('pdf-exported', pdfBytes)
  } catch (error) {
    console.error('Export error:', error)
    emit('error', error)
  } finally {
    isProcessing.value = false
  }
}

const clearFile = () => {
  fileName.value = ''
  hasPDF.value = false
  watermarks.value = []
  editor?.clear()
  hasContent.value = false
  if (fileInput.value) fileInput.value.value = ''
}
</script>

<style scoped>
.pdf-editor-wrapper {
  width: 100%;
  max-width: 900px;
  margin: 0 auto;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
  border: 1px solid rgba(0, 217, 255, 0.2);
}

.editor-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  padding-bottom: 15px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.editor-title {
  color: #00d9ff;
  font-size: 18px;
  font-weight: 600;
  margin: 0;
}

.header-actions {
  display: flex;
  gap: 10px;
}

.action-btn {
  padding: 8px 16px;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.3s ease;
  font-size: 14px;
}

.watermark-btn {
  background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
  color: white;
}

.watermark-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(245, 87, 108, 0.4);
}

.export-btn {
  background: linear-gradient(135deg, #00d9ff 0%, #00ff88 100%);
  color: #1a1a2e;
}

.export-btn:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 217, 255, 0.4);
}

.action-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.toolbar-section {
  display: flex;
  align-items: center;
  gap: 15px;
  margin-bottom: 15px;
}

.upload-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 20px;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  font-weight: 500;
  transition: all 0.3s ease;
}

.upload-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
}

.icon {
  font-size: 18px;
}

.file-info {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  background: rgba(0, 217, 255, 0.1);
  border-radius: 6px;
  color: #00d9ff;
  font-size: 14px;
}

.clear-btn {
  background: none;
  border: none;
  color: #ff6b6b;
  cursor: pointer;
  font-size: 20px;
  line-height: 1;
  padding: 0 4px;
}

.clear-btn:hover {
  color: #ff0000;
}

.editor-container {
  background: #16213e;
  border-radius: 8px;
  overflow: hidden;
  margin-bottom: 15px;
}

.rich-text-editor {
  min-height: 400px;
}

.watermark-panel {
  background: rgba(240, 147, 251, 0.1);
  border: 1px solid rgba(240, 147, 251, 0.3);
  border-radius: 8px;
  padding: 15px;
  margin-bottom: 15px;
}

.watermark-panel h4 {
  color: #f093fb;
  margin: 0 0 10px 0;
  font-size: 14px;
}

.watermark-panel ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.watermark-panel li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
  color: #eee;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.remove-wm-btn {
  padding: 4px 12px;
  background: #f5576c;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 12px;
  transition: all 0.2s ease;
}

.remove-wm-btn:hover {
  background: #ff0000;
}

.image-replace-section {
  background: rgba(0, 217, 255, 0.1);
  border: 1px solid rgba(0, 217, 255, 0.3);
  border-radius: 8px;
  padding: 15px;
}

.image-replace-section h4 {
  color: #00d9ff;
  margin: 0 0 10px 0;
  font-size: 14px;
}

.replace-image-btn {
  padding: 8px 16px;
  background: transparent;
  color: #00d9ff;
  border: 1px solid #00d9ff;
  border-radius: 6px;
  cursor: pointer;
  transition: all 0.3s ease;
}

.replace-image-btn:hover {
  background: #00d9ff;
  color: #1a1a2e;
}
</style>

// src/components/react/PdfEditor.tsx
import React, { useRef, useState, useEffect, useCallback } from "react";
import { PDFParser, PDFModifier } from "../../core/pdf-parser";
import { RichTextEditor, EditorConfig } from "../../core/rich-text-editor";

interface PdfEditorProps {
  placeholder?: string;
  readOnly?: boolean;
  initialContent?: string;
  onContentChange?: (data: { html: string; delta: any }) => void;
  onPdfLoaded?: (data: { pages: any[]; watermarks: any[] }) => void;
  onPdfExported?: (pdfBytes: ArrayBuffer) => void;
  onError?: (error: any) => void;
}

const PdfEditor: React.FC<PdfEditorProps> = ({
  placeholder = "请输入或粘贴PDF内容...",
  readOnly = false,
  initialContent = "",
  onContentChange,
  onPdfLoaded,
  onPdfExported,
  onError,
}) => {
  const editorRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const imageInputRef = useRef<HTMLInputElement>(null);

  const [fileName, setFileName] = useState<string>("");
  const [hasPDF, setHasPDF] = useState<boolean>(false);
  const [hasContent, setHasContent] = useState<boolean>(false);
  const [isProcessing, setIsProcessing] = useState<boolean>(false);
  const [watermarks, setWatermarks] = useState<any[]>([]);

  const editorInstance = useRef<RichTextEditor | null>(null);
  const pdfParserRef = useRef<PDFParser | null>(null);
  const pdfModifierRef = useRef<PDFModifier | null>(null);

  useEffect(() => {
    if (editorRef.current && !editorInstance.current) {
      const config: EditorConfig = {
        placeholder,
        readOnly,
        onContentChange: (html, delta) => {
          setHasContent(!!html && html !== "<p><br></p>");
          onContentChange?.({ html, delta });
        },
        onImageUpload: async (file: File): Promise<string> => {
          return new Promise((resolve) => {
            const reader = new FileReader();
            reader.onload = (e) => resolve(e.target?.result as string);
            reader.readAsDataURL(file);
          });
        },
      };

      editorInstance.current = new RichTextEditor(editorRef.current, config);

      if (initialContent) {
        editorInstance.current.setContent(initialContent);
        setHasContent(true);
      }
    }

    if (!pdfParserRef.current) {
      pdfParserRef.current = new PDFParser();
    }

    if (!pdfModifierRef.current) {
      pdfModifierRef.current = new PDFModifier();
    }

    return () => {
      if (editorInstance.current) {
        editorInstance.current.destroy();
        editorInstance.current = null;
      }
    };
  }, []);

  const handleFileUpload = useCallback(
    async (event: React.ChangeEvent<HTMLInputElement>) => {
      const file = event.target.files?.[0];

      if (file && file.type === "application/pdf") {
        try {
          setFileName(file.name);
          setIsProcessing(true);

          const pages = await pdfParserRef.current!.loadPDF(file);
          setHasPDF(true);

          let fullContent = "";
          pages.forEach((page, index) => {
            if (index > 0) fullContent += "<br/><br/>";
            fullContent += `<h2>第 ${page.pageNumber} 页</h2>`;
            fullContent += `<p>${page.textContent}</p>`;
          });

          setTimeout(() => {
            editorInstance.current?.setContent(fullContent);
            setHasContent(true);
          }, 100);

          const detectedWatermarks =
            await pdfParserRef.current!.detectWatermarks();
          setWatermarks(detectedWatermarks);

          onPdfLoaded?.({ pages, watermarks: detectedWatermarks });
        } catch (error) {
          console.error("PDF loading error:", error);
          onError?.(error);
        } finally {
          setIsProcessing(false);
        }
      }
    },
    [onPdfLoaded, onError],
  );

  const handleImageReplace = useCallback(
    async (event: React.ChangeEvent<HTMLInputElement>) => {
      const file = event.target.files?.[0];

      if (file && pdfParserRef.current?.getPDFBytes()) {
        try {
          setIsProcessing(true);
          await pdfModifierRef.current!.replaceImage(
            pdfParserRef.current.getPDFBytes()!,
            0,
            file,
          );
          alert("图片已准备替换，导出时将生效");
        } catch (error) {
          console.error("Image replacement error:", error);
          onError?.(error);
        } finally {
          setIsProcessing(false);
        }
      }
    },
    [onError],
  );

  const removeWatermark = useCallback(async () => {
    if (!pdfParserRef.current?.getPDFBytes() || !watermarks.length) return;

    try {
      setIsProcessing(true);
      const watermarkTexts = watermarks.map((wm) => wm.content);
      await pdfModifierRef.current!.removeWatermark(
        pdfParserRef.current.getPDFBytes()!,
        watermarkTexts,
      );
      setWatermarks([]);
      alert("水印已移除，将在导出时生效");
    } catch (error) {
      console.error("Watermark removal error:", error);
      onError?.(error);
    } finally {
      setIsProcessing(false);
    }
  }, [watermarks, onError]);

  const removeSpecificWatermark = useCallback(
    async (index: number) => {
      const wm = watermarks[index];
      if (!pdfParserRef.current?.getPDFBytes()) return;

      try {
        setIsProcessing(true);
        await pdfModifierRef.current!.removeWatermark(
          pdfParserRef.current.getPDFBytes()!,
          [wm.content],
        );
        setWatermarks((prev) => prev.filter((_, i) => i !== index));
      } catch (error) {
        console.error("Error removing watermark:", error);
        onError?.(error);
      } finally {
        setIsProcessing(false);
      }
    },
    [watermarks, onError],
  );

  const exportPDF = useCallback(async () => {
    if (!editorInstance.current || !hasContent) return;

    try {
      setIsProcessing(true);
      const content = editorInstance.current.getContent();
      const pdfBytes = await pdfModifierRef.current!.exportToPDF(content);

      const blob = new Blob([new Uint8Array(pdfBytes)], {
        type: "application/pdf",
      });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `edited-document-${Date.now()}.pdf`;
      a.click();
      URL.revokeObjectURL(url);

      onPdfExported?.(pdfBytes.buffer as ArrayBuffer);
    } catch (error) {
      console.error("Export error:", error);
      onError?.(error);
    } finally {
      setIsProcessing(false);
    }
  }, [hasContent, onPdfExported, onError]);

  const clearFile = useCallback(() => {
    setFileName("");
    setHasPDF(false);
    setWatermarks([]);
    editorInstance.current?.clear();
    setHasContent(false);
    if (fileInputRef.current) fileInputRef.current.value = "";
  }, []);

  return (
    <div className="pdf-editor-wrapper">
      <div className="editor-header">
        <h3 className="editor-title">文档编辑</h3>
        <div className="header-actions">
          {hasPDF && (
            <button
              onClick={removeWatermark}
              className="action-btn watermark-btn"
              disabled={isProcessing}
            >
              {isProcessing ? "处理中..." : "去除水印"}
            </button>
          )}
          <button
            onClick={exportPDF}
            className="action-btn export-btn"
            disabled={!hasContent}
          >
            导出PDF
          </button>
        </div>
      </div>

      <div className="toolbar-section">
        <input
          type="file"
          ref={fileInputRef}
          accept=".pdf"
          onChange={handleFileUpload}
          style={{ display: "none" }}
        />
        <button
          onClick={() => fileInputRef.current?.click()}
          className="upload-btn"
        >
          <span className="icon">📄</span>
          上传PDF文件
        </button>

        {fileName && (
          <div className="file-info">
            <span className="file-name">{fileName}</span>
            <button onClick={clearFile} className="clear-btn">
              ×
            </button>
          </div>
        )}
      </div>

      <div className="editor-container">
        <div ref={editorRef} className="rich-text-editor"></div>
      </div>

      {watermarks.length > 0 && (
        <div className="watermark-panel">
          <h4>检测到的水印：</h4>
          <ul>
            {watermarks.map((wm, index) => (
              <li key={index}>
                {wm.content}
                <button
                  onClick={() => removeSpecificWatermark(index)}
                  className="remove-wm-btn"
                >
                  移除
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}

      {hasPDF && (
        <div className="image-replace-section">
          <h4>图片替换</h4>
          <input
            type="file"
            ref={imageInputRef}
            accept="image/*"
            onChange={handleImageReplace}
            style={{ display: "none" }}
          />
          <button
            onClick={() => imageInputRef.current?.click()}
            className="replace-image-btn"
          >
            选择新图片替换
          </button>
        </div>
      )}

      <style>{`
        .pdf-editor-wrapper {
          width: 100%;
          max-width: 900px;
          margin: 0 auto;
          background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
          border-radius: 12px;
          padding: 20px;
          box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
          border: 1px solid rgba(0, 217, 255, 0.2);
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        }

        .editor-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
          padding-bottom: 15px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.1);
        }

        .editor-title {
          color: #00d9ff;
          font-size: 18px;
          font-weight: 600;
          margin: 0;
        }

        .header-actions {
          display: flex;
          gap: 10px;
        }

        .action-btn {
          padding: 8px 16px;
          border: none;
          border-radius: 6px;
          cursor: pointer;
          font-weight: 500;
          transition: all 0.3s ease;
          font-size: 14px;
        }

        .watermark-btn {
          background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
          color: white;
        }

        .watermark-btn:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(245, 87, 108, 0.4);
        }

        .export-btn {
          background: linear-gradient(135deg, #00d9ff 0%, #00ff88 100%);
          color: #1a1a2e;
        }

        .export-btn:hover:not(:disabled) {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(0, 217, 255, 0.4);
        }

        .action-btn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .toolbar-section {
          display: flex;
          align-items: center;
          gap: 15px;
          margin-bottom: 15px;
        }

        .upload-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 20px;
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          border: none;
          border-radius: 8px;
          cursor: pointer;
          font-weight: 500;
          transition: all 0.3s ease;
          font-size: 14px;
        }

        .upload-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
        }

        .icon {
          font-size: 18px;
        }

        .file-info {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 8px 12px;
          background: rgba(0, 217, 255, 0.1);
          border-radius: 6px;
          color: #00d9ff;
          font-size: 14px;
        }

        .clear-btn {
          background: none;
          border: none;
          color: #ff6b6b;
          cursor: pointer;
          font-size: 20px;
          line-height: 1;
          padding: 0 4px;
        }

        .clear-btn:hover {
          color: #ff0000;
        }

        .editor-container {
          background: #16213e;
          border-radius: 8px;
          overflow: hidden;
          margin-bottom: 15px;
        }

        .rich-text-editor {
          min-height: 400px;
        }

        .watermark-panel {
          background: rgba(240, 147, 251, 0.1);
          border: 1px solid rgba(240, 147, 251, 0.3);
          border-radius: 8px;
          padding: 15px;
          margin-bottom: 15px;
        }

        .watermark-panel h4 {
          color: #f093fb;
          margin: 0 0 10px 0;
          font-size: 14px;
        }

        .watermark-panel ul {
          list-style: none;
          padding: 0;
          margin: 0;
        }

        .watermark-panel li {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 8px 0;
          color: #eee;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
        }

        .remove-wm-btn {
          padding: 4px 12px;
          background: #f5576c;
          color: white;
          border: none;
          border-radius: 4px;
          cursor: pointer;
          font-size: 12px;
          transition: all 0.2s ease;
        }

        .remove-wm-btn:hover {
          background: #ff0000;
        }

        .image-replace-section {
          background: rgba(0, 217, 255, 0.1);
          border: 1px solid rgba(0, 217, 255, 0.3);
          border-radius: 8px;
          padding: 15px;
        }

        .image-replace-section h4 {
          color: #00d9ff;
          margin: 0 0 10px 0;
          font-size: 14px;
        }

        .replace-image-btn {
          padding: 8px 16px;
          background: transparent;
          color: #00d9ff;
          border: 1px solid #00d9ff;
          border-radius: 6px;
          cursor: pointer;
          transition: all 0.3s ease;
          font-size: 14px;
        }

        .replace-image-btn:hover {
          background: #00d9ff;
          color: #1a1a2e;
        }
      `}</style>
    </div>
  );
};

export default PdfEditor;
